"""empty message

Revision ID: 085961bebc4f
Revises: 4245a553186b
Create Date: 2023-08-22 03:56:45.986875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '085961bebc4f'
down_revision = '4245a553186b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follower',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follower')
    # ### end Alembic commands ###
